// Assembly WebDev.WebHost, Version 9.0.0.0

[assembly: System.Reflection.AssemblyVersion("9.0.0.0")]
[assembly: System.Reflection.AssemblyCompany("Microsoft Corporation")]
[assembly: System.Reflection.AssemblyProduct("Microsoft (R) Visual Studio (R) 2008")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 Microsoft Corporation. All rights reserved.")]
//[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.Default)]
//[assembly: System.CLSCompliant(false)]
[assembly: System.Reflection.AssemblyTitle("WebDev.WebHost.dll")]
[assembly: System.Reflection.AssemblyDescription("WebDev.WebHost.dll")]
[assembly: System.Reflection.AssemblyDefaultAlias("WebDev.WebHost.dll")]
//[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyFileVersion("9.0.21022.8")]
[assembly: System.Reflection.AssemblyInformationalVersion("9.0.21022.8")]
//[assembly: System.Resources.SatelliteContractVersion("9.0.0.0")]
[assembly: System.Resources.NeutralResourcesLanguage("zh-CN")]
//[assembly: System.Reflection.AssemblyDelaySign(true)]
//[assembly: System.Reflection.AssemblyKeyFile(@"f:\dd\tools\devdiv\FinalPublicKey.snk")]
//[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum, SkipVerification=true)]
